# Generated by Django 4.2 on 2023-04-11 05:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('images', models.ImageField(blank=True, null=True, upload_to='announcement/images', verbose_name='Изображения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('price', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000), django.core.validators.RegexValidator(message='Цена должна быть: договорная или 0 до 1000000', regex='\\bдоговорная\\b')], verbose_name='Цена')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Оплата рекламы')),
                ('category', models.CharField(choices=[('SA', 'сельско-хозяйственные животные'), ('DO', 'собаки'), ('CA', 'кошки'), ('BE', 'птицы'), ('FI', 'рыбки'), ('RO', 'грызуны'), ('RE', 'рептилии'), ('AM', 'амфибии'), ('IN', 'насекомые'), ('AR', 'паукообразные'), ('HS', 'хостелы/приюты'), ('VC', 'вет.клиники'), ('VE', 'ветеринары'), ('ZN', 'зоо няни'), ('ZM', 'зоо магазины')], max_length=2)),
                ('location', models.CharField(choices=[('KYR', 'Кыргызстан'), ('BIS', 'Бищкек'), ('OSH', 'Ош'), ('NAR', 'Нарын'), ('ISS', 'Иссык-Куль'), ('BAT', 'Баткен'), ('TAL', 'Талас'), ('JAL', 'Джалал-Абад')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_id создавший объявление')),
            ],
        ),
    ]
