# Generated by Django 4.2 on 2023-04-11 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Цена должна быть: договорная или 0 до 1000000', regex='^[0-9]{1.6}$'), django.core.validators.RegexValidator(message='Цена должна быть: договорная или 0 до 1000000', regex='\\bдоговорная\\b')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
