# Generated by Django 4.2 on 2023-04-12 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Оъявление', 'verbose_name_plural': 'Оъявления'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно/Неактивно'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('сельско-хозяйственные', 'сельско-хозяйственные'), ('собаки', 'собаки'), ('кошки', 'кошки'), ('птицы', 'птицы'), ('рыбки', 'рыбки'), ('грызуны', 'грызуны'), ('рептилии', 'рептилии'), ('амфибии', 'амфибии'), ('насекомые', 'насекомые'), ('паукообразные', 'паукообразные'), ('хостелы/приюты', 'хостелы/приюты'), ('вет.клиники', 'вет.клиники'), ('ветеринары', 'ветеринары'), ('зоо няни', 'зоо няни'), ('зоо магазины', 'зоо магазины')], max_length=25),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(choices=[('Кыргызстан', 'Кыргызстан'), ('Бищкек', 'Бищкек'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Иссык-Куль', 'Иссык-Куль'), ('Баткен', 'Баткен'), ('Талас', 'Талас'), ('Джалал-Абад', 'Джалал-Абад')], max_length=15),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Цена должна быть: договорная или 0 до 1000000', regex='^(договорная|\\d{1,7})$')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
