# Generated by Django 4.2 on 2023-04-11 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Цена должна быть: договорная или 0 до 1000000', regex='^(договорная|\\d{1,6})$')], verbose_name='Цена'),
        ),
    ]
