# Generated by Django 4.2 on 2023-04-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_announcement_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Оъявление', 'verbose_name_plural': 'Оъявления'},
        ),
    ]
