# Generated by Django 4.2 on 2023-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_announcement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(choices=[('Кыргызстан', 'Кыргызстан'), ('Бищкек', 'Бищкек'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Иссык-Куль', 'Иссык-Куль'), ('Баткен', 'Баткен'), ('Талас', 'Талас'), ('Джалал-Абад', 'Джалал-Абад')], max_length=15),
        ),
    ]
