# Generated by Django 4.2 on 2023-04-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_announcement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('сельско-хозяйственные', 'сельско-хозяйственные'), ('собаки', 'собаки'), ('кошки', 'кошки'), ('птицы', 'птицы'), ('рыбки', 'рыбки'), ('грызуны', 'грызуны'), ('рептилии', 'рептилии'), ('амфибии', 'амфибии'), ('насекомые', 'насекомые'), ('паукообразные', 'паукообразные'), ('хостелы/приюты', 'хостелы/приюты'), ('вет.клиники', 'вет.клиники'), ('ветеринары', 'ветеринары'), ('зоо няни', 'зоо няни'), ('зоо магазины', 'зоо магазины')], max_length=25),
        ),
    ]
