# Generated by Django 4.1.7 on 2023-03-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_block_alter_chat_block_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='block_user',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_user', to='chat.block'),
        ),
    ]
