# Generated by Django 4.2 on 2023-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
