# Generated by Django 4.2 on 2023-04-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_phone_number_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
